version: "3"

services:
  package:
    image: gradle
    container_name: package
    volumes:
      - ../:/opt/web/code
    working_dir: /opt/web/code/docker
    command: "./package.sh"
    links:
      - mysql

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_USER: "root"  
      MYSQL_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:  
      - ./mysql:/var/lib/mysql
  catete_db:
    image: mysql
    container_name: catete_db
    command: bash -c "while [ `mysql -uroot -hmysql 2>/dev/null || echo 'sleep'` ];do sleep 1;done;mysql -uroot -hmysql -e 'create database order_d;create database product_d;create database price_d;create database cart_d;create database inventory_d;create database refund_d;create database user_d;'"
    links:
      - mysql
    
  # orderService:
  #   image: java:8
  #   container_name: orderService
  #   ports:
  #     - 20000:20000
  #   volumes:
  #     - ./orderService:/opt/web/code/orderService
  #   working_dir: /opt/web/code/orderService
  #   command: bash -c 'while [ ! -d bin ];do sleep 1;done;./bin/orderService'
  #   links:
  #     - mysql
  #     - priceService
  #   environment:
  #     DB_HOST: mysql
  #     DB_ON_CREATE_DB: order_d
  #     SERVICE_PORT: 20000
  #     PRICE_SERVICE_HOST: priceService
  #     PRICE_SERVICE_PORT: 20200

  productService:
    image: java:8
    container_name: productService
    ports:
      - 20100:20100
    volumes:
      - ./productService:/opt/web/code/productService
    working_dir: /opt/web/code/productService
    command: bash -c 'while [ ! -d bin ];do sleep 1;done;./bin/productService'
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_ON_CREATE_DB: product_d
      SERVICE_PORT: 20100

  priceService:
    image: java:8
    container_name: priceService
    ports:
      - 20200:20200
    volumes:
      - ./priceService:/opt/web/code/priceService
    working_dir: /opt/web/code/priceService
    command: bash -c 'while [ ! -d bin ];do sleep 1;done;./bin/priceService'
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_ON_CREATE_DB: price_d
      SERVICE_PORT: 20200

  # cartService:
  #   image: java:8
  #   container_name: cartService
  #   ports:
  #     - 20300:20300
  #   volumes:
  #     - ./cartService:/opt/web/code/cartService
  #   working_dir: /opt/web/code/cartService
  #   command: bash -c 'while [ ! -d bin ];do sleep 1;done;./bin/cartService'
  #   links:
  #     - mysql
  #     - priceService
  #   environment:
  #     DB_HOST: mysql
  #     DB_ON_CREATE_DB: cart_d
  #     SERVICE_PORT: 20300
  #     PRICE_SERVICE_HOST: priceService
  #     PRICE_SERVICE_PORT: 20200

  # inventoryService:
  #   image: java:8
  #   container_name: inventoryService
  #   ports:
  #     - 20400:20400
  #   volumes:
  #     - ./inventoryService:/opt/web/code/inventoryService
  #   working_dir: /opt/web/code/inventoryService
  #   command: bash -c 'while [ ! -d bin ];do sleep 1;done;./bin/inventoryService'
  #   links:
  #     - mysql
  #   environment:
  #     DB_HOST: mysql
  #     DB_ON_CREATE_DB: inventory_d
  #     SERVICE_PORT: 20400

  # refundService:
  #   image: java:8
  #   container_name: refundService
  #   ports:
  #     - 20500:20500
  #   volumes:
  #     - ./refundService:/opt/web/code/refundService
  #   working_dir: /opt/web/code/refundService
  #   command: bash -c 'while [ ! -d bin ];do sleep 1;done;./bin/refundService'
  #   links:
  #     - mysql
  #     - orderService
  #     - priceService
  #   environment:
  #     DB_HOST: mysql
  #     DB_ON_CREATE_DB: refund_d
  #     SERVICE_PORT: 20500
  #     ORDER_SERVICE_HOST: orderService
  #     ORDER_SERVICE_PORT: 20000
  #     PRICE_SERVICE_HOST: priceService
  #     PRICE_SERVICE_PORT: 20200

  userService:
    image: java:8
    container_name: userService
    ports:
      - 20600:20600
    volumes:
      - ./userService:/opt/web/code/userService
    working_dir: /opt/web/code/userService
    command: bash -c 'while [ ! -d bin ];do sleep 1;done;./bin/userService'
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_ON_CREATE_DB: user_d
      SERVICE_PORT: 20600

  web:  
    image: nginx  
    ports:  
      - 8888:80
    volumes:  
      - ./nginx/site.conf:/etc/nginx/nginx.conf:ro
      - ./nginx:/nginx
    working_dir: /nginx
    environment:
      - NGINX_HOST=127.0.0.1
      - NGINX_PORT=80
    command: ["nginx", "-g", "daemon off;"]
    links:
      # - orderService
      - productService
      - priceService
      # - cartService
      # - inventoryService
      # - refundService
      - userService
  
  













