version: "3"

services:
  package:
    image: gradle
    container_name: package
    volumes:
      - ../:/opt/web/code
    working_dir: /opt/web/code/docker
    command: ["./package.sh"]
    links:
      - orderMysql
      - producrMysql
      - priceMysql
      - cartMysql
      - inventoryMysql
      - refundMysql
      - userMysql

  orderService:
    image: java:8
    container_name: orderService
    ports:
      - 20000:20000
    volumes:
      - ./orderService:/opt/web/code/orderService
    working_dir: /opt/web/code/orderService
    command: ["./bin/orderService"]
    links:
      - orderMysql
      - priceService
    environment:
      DB_HOST: orderMysql
      SERVICE_PORT: 20000
      PRICE_SERVICE_HOST: priceService
      PRICE_SERVICE_PORT: 20200
  orderMysql:
    image: mysql
    container_name: orderMysql
    environment:
      MYSQL_USER: "root"  
      MYSQL_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: ""
      ON_CREATE_DB: "data_store"
      MYSQL_DATABASE: "data_store"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:  
      - ./orderMysql:/var/lib/mysql

  productService:
    image: java:8
    container_name: productService
    ports:
      - 20100:20100
    volumes:
      - ./productService:/opt/web/code/productService
    working_dir: /opt/web/code/productService
    command: ["./bin/productService"]
    links:
      - producrMysql
    environment:
      DB_HOST: producrMysql
      SERVICE_PORT: 20100
  producrMysql:
    image: mysql
    container_name: producrMysql
    environment:
      MYSQL_USER: "root"  
      MYSQL_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: ""
      ON_CREATE_DB: "data_store"
      MYSQL_DATABASE: "data_store"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:  
      - ./producrMysql:/var/lib/mysql

  priceService:
    image: java:8
    container_name: priceService
    ports:
      - 20200:20200
    volumes:
      - ./priceService:/opt/web/code/priceService
    working_dir: /opt/web/code/priceService
    command: ["./bin/priceService"]
    links:
      - priceMysql
    environment:
      DB_HOST: priceMysql
      SERVICE_PORT: 20200
  priceMysql:
    image: mysql
    container_name: priceMysql
    environment:
      MYSQL_USER: "root"  
      MYSQL_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: ""
      ON_CREATE_DB: "data_store"
      MYSQL_DATABASE: "data_store"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:  
      - ./priceMysql:/var/lib/mysql

  cartService:
    image: java:8
    container_name: cartService
    ports:
      - 20300:20300
    volumes:
      - ./cartService:/opt/web/code/cartService
    working_dir: /opt/web/code/cartService
    command: ["./bin/cartService"]
    links:
      - cartMysql
      - priceService
    environment:
      DB_HOST: cartMysql
      SERVICE_PORT: 20300
      PRICE_SERVICE_HOST: priceService
      PRICE_SERVICE_PORT: 20200
  cartMysql:
    image: mysql
    container_name: cartMysql
    environment:
      MYSQL_USER: "root"  
      MYSQL_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: ""
      ON_CREATE_DB: "data_store"
      MYSQL_DATABASE: "data_store"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:  
      - ./cartMysql:/var/lib/mysql

  inventoryService:
    image: java:8
    container_name: inventoryService
    ports:
      - 20400:20400
    volumes:
      - ./inventoryService:/opt/web/code/inventoryService
    working_dir: /opt/web/code/inventoryService
    command: ["./bin/inventoryService"]
    links:
      - inventoryMysql
    environment:
      DB_HOST: inventoryMysql
      SERVICE_PORT: 20400
  inventoryMysql:
    image: mysql
    container_name: inventoryMysql
    environment:
      MYSQL_USER: "root"  
      MYSQL_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: ""
      ON_CREATE_DB: "data_store"
      MYSQL_DATABASE: "data_store"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:  
      - ./inventoryMysql:/var/lib/mysql

  refundService:
    image: java:8
    container_name: refundService
    ports:
      - 20500:20500
    volumes:
      - ./refundService:/opt/web/code/refundService
    working_dir: /opt/web/code/refundService
    command: ["./bin/refundService"]
    links:
      - refundMysql
      - orderService
      - priceService
    environment:
      DB_HOST: refundMysql
      SERVICE_PORT: 20500
      ORDER_SERVICE_HOST: orderService
      ORDER_SERVICE_PORT: 20000
      PRICE_SERVICE_HOST: priceService
      PRICE_SERVICE_PORT: 20200
  refundMysql:
    image: mysql
    container_name: refundMysql
    environment:
      MYSQL_USER: "root"  
      MYSQL_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: ""
      ON_CREATE_DB: "data_store"
      MYSQL_DATABASE: "data_store"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:  
      - ./refundMysql:/var/lib/mysql

  userService:
    image: java:8
    container_name: userService
    ports:
      - 20600:20600
    volumes:
      - ./userService:/opt/web/code/userService
    working_dir: /opt/web/code/userService
    command: ["./bin/userService"]
    links:
      - userMysql
    environment:
      DB_HOST: userMysql
      SERVICE_PORT: 20600
  userMysql:
    image: mysql
    container_name: userMysql
    environment:
      MYSQL_USER: "root"  
      MYSQL_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: ""
      ON_CREATE_DB: "data_store"
      MYSQL_DATABASE: "data_store"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:  
      - ./userMysql:/var/lib/mysql
  
  













