CREATE TABLE inventories (
  id INT PRIMARY KEY AUTO_INCREMENT,
  store_id VARCHAR(255) NOT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE inventory_items (
  id INT PRIMARY KEY AUTO_INCREMENT,
  inventory_id VARCHAR(255) NOT NULL,
  product_id VARCHAR(255) NOT NULL,
  quantity VARCHAR(255) NOT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
